In [1]:
pip install tensorflow==1.0.0

     |████████████████████████████████| 44.5MB 93kB/s 
  Found existing installation: tensorflow 2.4.1
    Uninstalling tensorflow-2.4.1:
      Successfully uninstalled tensorflow-2.4.1


In [2]:
import tensorflow as tf
import numpy as np
import pprint
tf.set_random_seed(777)
pp = pprint.PrettyPrinter(indent=4)
sess = tf.InteractiveSession()
# Simple ID array and slicing
t = np.array([0., 1., 2., 3., 4., 5., 6.])
pp.pprint(t)
print(t.ndim)
print(t.shape)
print(t[0], t[1], t[-1])
print(t[2:5], t[4:-1])
print(t[:2], t[3:])
# 2D array
t = np.array([[1.,2.,3.],[4.,5.,6.], [7.,8.,9.], [10.,11.,12.]])
pp.pprint(t)
print(t.ndim)
print(t.shape)
# Shape, Rank, Axis
t = tf.constant([1,2,3,4])
tf.shape(t).eval()

t = tf.constant([[1,2],[3,4]])
tf.shape(t).eval()

t = tf.constant([[[[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]],[[13, 14, 15, 16], [17, 18, 19, 20], [21, 22, 23, 24]]]])
tf.shape(t).eval()

# Matmul VS multiply
matrix1 = tf.constant([[1., 2.], [3., 4.]])
matrix2 = tf.constant([[1.],[2.]])
print('Matrix 1 shape', matrix1.shape)
print('Matrix 2 shape', matrix2.shape)
tf.matmul(matrix1, matrix2).eval() 

(matrix1*matrix2).eval()

# Broadcasting
matrix1 = tf.constant([[3., 3.]])
matrix2 = tf.constant([[2., 2.]])
(matrix1 + matrix2).eval() 

matrix1 = tf.constant([[1., 2.]])
matrix2 = tf.constant(3.)
(matrix1 + matrix2).eval() 

matrix1 = tf.constant([[1., 2.]])
matrix2 = tf.constant([3., 4.])
(matrix1 + matrix2).eval() 

matrix1 = tf.constant([[1., 2.]])
matrix2 = tf.constant([[3.], [4.]])
(matrix1 + matrix2).eval() 

# Reduce mean
tf.reduce_mean([1, 2], axis = 0).eval()

x = [[1., 2.], [3., 4.]]
tf.reduce_mean(x).eval()

tf.reduce_mean(x, axis = 0).eval()

tf.reduce_mean(x, axis = 1).eval()

tf.reduce_mean(x, axis = -1).eval() # the most inner layer (in this case same with axis = 1)

# Reduce sum
x = [[1., 2.], [3., 4.]]
tf.reduce_sum(x).eval()

tf.reduce_sum(x, axis = 0).eval()

tf.reduce_sum(x, axis = -1).eval()

tf.reduce_mean(tf.reduce_sum(x, axis = -1)).eval()

# Argmax
x = [[0, 1, 2], [2, 1, 0]]
tf.argmax(x, axis = 0).eval()
tf.argmax(x, axis = 1).eval()
tf.argmax(x, axis = -1).eval()

# Reshape
t = np.array([[[0, 1, 2], 
               [3, 4, 5]],
              
              [[6, 7, 8], 
               [9, 10, 11]]])
t.shape
tf.reshape(t, shape = [-1, 3]).eval()

tf.reshape(t, shape = [-1,1, 3]).eval()

# Reshape (squeeze, expand)
tf.squeeze([[0], [1], [2]]).eval()

tf.expand_dims([0, 1, 2], 1).eval()

# One hot
tf.one_hot([[0], [1], [2], [0]], depth=3).eval()
t = tf.one_hot([[0], [1], [2], [0]], depth =3)
tf.reshape(t, shape = [-1, 3]).eval()

# Casting
tf.cast([1.8, 2.2, 3.3, 4.9], tf.int32).eval()
tf.cast([True, False, 1 ==1, 0==1], tf.int32).eval()

# Stack
x = [1, 4]
y = [2, 5]
z = [3, 6]
# Pack along first dim.
tf.stack([x, y, z]).eval()
tf.stack([x, y, z], axis = 1).eval()

# Ones and Zeros like
x = [[0,1,2], [2,1,0]]
tf.ones_like(x).eval()
tf.zeros_like(x).eval()

# Zip
for x, y in zip([1,2,3], [4,5,6]) :
  print(x, y)
for x, y, z in zip([1,2,3], [4,5,6], [7,8,9]) :
  print(x, y, z)

/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/dtypes.py:471: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/dtypes.py:472: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/dtypes.py:473: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/dtypes.py:474: FutureWarning: Passing (type, 1) or 

array([0., 1., 2., 3., 4., 5., 6.])
1
(7,)
0.0 1.0 6.0
[2. 3. 4.] [4. 5.]
[0. 1.] [3. 4. 5. 6.]
array([[ 1.,  2.,  3.],
       [ 4.,  5.,  6.],
       [ 7.,  8.,  9.],
       [10., 11., 12.]])
2
(4, 3)
Matrix 1 shape (2, 2)
Matrix 2 shape (2, 1)
1 4
2 5
3 6
1 4 7
2 5 8
3 6 9
