In [1]:
pip install tensorflow==1.0.0

     |████████████████████████████████| 44.5MB 84kB/s 
  Found existing installation: tensorflow 2.4.1
    Uninstalling tensorflow-2.4.1:
      Successfully uninstalled tensorflow-2.4.1


In [2]:
import tensorflow as tf
x1_data = [73., 93., 89., 96., 73.]
x2_data = [80., 88., 91., 98., 66.]
x3_data = [75., 93., 90., 100., 70.]
y_data = [152., 185., 180., 196., 142.]

x1 = tf.placeholder(tf.float32)
x2 = tf.placeholder(tf.float32)
x3 = tf.placeholder(tf.float32)
Y = tf.placeholder(tf.float32)

w1 = tf.Variable(tf.random_normal([1]), name='weight1')
w2 = tf.Variable(tf.random_normal([1]), name='weight2')
w3 = tf.Variable(tf.random_normal([1]), name='weight3')
b = tf.Variable(tf.random_normal([1]), name='bias')
hypothesis = x1 * w1 + x2 * w2 + x3 * w3 + b

#cost/loss function
cost = tf.reduce_mean(tf.square(hypothesis - Y))
# minimize. Need a very small learning rate for this data set
optimizer = tf.train.GradientDescentOptimizer(learning_rate = 1e-5)
train = optimizer.minimize(cost)

#Launch the graph in a session.
sess = tf.Session()
sess.run(tf.global_variables_initializer())
for step in range(2001):
  cost_val, hy_val, _ = sess.run([cost, hypothesis, train], 
                                 feed_dict = {x1: x1_data, x2: x2_data, x3: x3_data, Y: y_data})
  if step % 10 == 0:
    print(step, "Cost: ", cost_val, "\nPrediction:\n", hy_val)

/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/dtypes.py:471: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/dtypes.py:472: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/dtypes.py:473: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/dtypes.py:474: FutureWarning: Passing (type, 1) or 

0 Cost:  6900.9507 
Prediction:
 [ 66.50651  104.01038   89.89676  101.531395  82.055145]
10 Cost:  52.31909 
Prediction:
 [139.74095 191.98029 176.60231 195.94768 149.14421]
20 Cost:  51.98686 
Prediction:
 [139.99017 192.22757 176.87325 196.23883 149.32304]
30 Cost:  51.718884 
Prediction:
 [140.0185  192.2095  176.8826  196.24518 149.2995 ]
40 Cost:  51.452076 
Prediction:
 [140.0461  192.19066 176.89116 196.25063 149.27539]
50 Cost:  51.186928 
Prediction:
 [140.0736  192.17188 176.89966 196.25604 149.25134]
60 Cost:  50.923126 
Prediction:
 [140.10103 192.15312 176.90816 196.26146 149.22739]
70 Cost:  50.66073 
Prediction:
 [140.12842 192.13448 176.91667 196.26689 149.20349]
80 Cost:  50.399708 
Prediction:
 [140.15572 192.11583 176.92513 196.27226 149.17966]
90 Cost:  50.140156 
Prediction:
 [140.1829  192.09721 176.93355 196.2776  149.15587]
100 Cost:  49.882122 
Prediction:
 [140.21005 192.0787  176.94194 196.28299 149.13217]
110 Cost:  49.625195 
Prediction:
 [140.23714 192.06

In [3]:
import tensorflow as tf
x_data = [[73., 80., 75.], [93., 88., 93.], [89., 91., 90.], [96., 98., 100.],[73., 66., 70.]]
y_data = [[152.], [185.], [180.], [196.], [142.]]
# placeholders for a tensor that will be always fed.
X = tf.placeholder(tf.float32, shape = [None, 3])
Y = tf.placeholder(tf.float32, shape = [None, 1])

W = tf.Variable(tf.random_normal([3, 1]), name = 'weight')
b = tf.Variable(tf.random_normal([1]), name = 'bias')

#Hypothesis
hypothesis = tf.matmul(X, W) + b
#Simplified cost/loss function
cost = tf.reduce_mean(tf.square(hypothesis - Y))
#Minimize
optimizer = tf.train.GradientDescentOptimizer(learning_rate = 1e-5)
train = optimizer.minimize(cost)

#Launch the graph in a session.
sess = tf.Session()
# Initializes global variables in the graph.
sess.run(tf.global_variables_initializer())

for step in range(2001) :
  cost_val, hyp_val, _ = sess.run([cost, hypothesis, train] ,feed_dict = {X: x_data, Y: y_data})
  if step % 10 == 0 :
    print(step, "Cost: ", cost_val, "\nPrediction: \n", hy_val)

0 Cost:  36744.76 
Prediction: 
 [144.24841 189.32399 178.19682 197.0547  145.63203]
10 Cost:  18.648594 
Prediction: 
 [144.24841 189.32399 178.19682 197.0547  145.63203]
20 Cost:  18.215305 
Prediction: 
 [144.24841 189.32399 178.19682 197.0547  145.63203]
30 Cost:  18.118755 
Prediction: 
 [144.24841 189.32399 178.19682 197.0547  145.63203]
40 Cost:  18.022728 
Prediction: 
 [144.24841 189.32399 178.19682 197.0547  145.63203]
50 Cost:  17.92725 
Prediction: 
 [144.24841 189.32399 178.19682 197.0547  145.63203]
60 Cost:  17.832245 
Prediction: 
 [144.24841 189.32399 178.19682 197.0547  145.63203]
70 Cost:  17.73775 
Prediction: 
 [144.24841 189.32399 178.19682 197.0547  145.63203]
80 Cost:  17.643803 
Prediction: 
 [144.24841 189.32399 178.19682 197.0547  145.63203]
90 Cost:  17.550406 
Prediction: 
 [144.24841 189.32399 178.19682 197.0547  145.63203]
100 Cost:  17.457462 
Prediction: 
 [144.24841 189.32399 178.19682 197.0547  145.63203]
110 Cost:  17.365005 
Prediction: 
 [144.24841

In [4]:
import tensorflow as tf
import numpy as np
from google.colab import drive
drive.mount('/gdrive', force_remount=True)
tf.set_random_seed(777)

xy = np.loadtxt('/gdrive/My Drive/Deep_learning_2102/data-01-test-score.csv', delimiter=',', dtype=np.float32)
x_data = xy[:, 0:-1]
y_data = xy[:, [-1]]

#Make sure the shap and data are OK
print(x_data.shape, x_data, len(x_data))
print(y_data.shape, y_data)

#placeholders for a tensor that will be always fed.
X = tf.placeholder(tf.float32, shape = [None, 3])
Y = tf.placeholder(tf.float32, shape = [None, 1])

W = tf.Variable(tf.random_normal([3,1]), name = 'weight')
b = tf.Variable(tf.random_normal([1]), name = 'bias')

#Hypothesis
hypothesis = tf.matmul(X, W) + b

#Simplified cost/loss function
cost = tf.reduce_mean(tf.square(hypothesis - Y))

#Minimize
optimizer = tf.train.GradientDescentOptimizer(learning_rate = 1e-5)
train = optimizer.minimize(cost)

#Launch the graph in a session.
sess = tf.Session()
#Initializes global variables in the graph
sess.run(tf.global_variables_initializer())
#Set up feed_dict variables inside the Loop.
for step in range(2001) :
  cost_val, hy_val, _ = sess.run([cost, hypothesis, train], feed_dict={X: x_data, Y: y_data})
  if step % 10 == 0:
    print(step, "Cost: ", cost_val, "\nPrediction: \n", hy_val)

# Ask my score
print("Your score will be ", sess.run(hypothesis, feed_dict={X: [[100, 70, 101]]}))
print("Other scores will be ", sess.run(hypothesis, feed_dict = {X: [[60,70,110], [90,100,80]]}))  

Mounted at /gdrive
(6, 3) [[ 73.  80.  75.]
 [ 93.  88.  93.]
 [ 89.  91.  90.]
 [ 96.  98. 100.]
 [ 73.  66.  70.]
 [ 53.  46.  55.]] 6
(6, 1) [[152.]
 [185.]
 [180.]
 [196.]
 [142.]
 [101.]]
0 Cost:  20100.084 
Prediction: 
 [[15.3530855]
 [25.620491 ]
 [21.435873 ]
 [23.021597 ]
 [21.901628 ]
 [17.103834 ]]
10 Cost:  10.269867 
Prediction: 
 [[147.50897]
 [184.4846 ]
 [177.95532]
 [193.47246]
 [143.07637]
 [106.42738]]
20 Cost:  9.295157 
Prediction: 
 [[148.4177 ]
 [185.55391]
 [179.02095]
 [194.63026]
 [143.88847]
 [107.01915]]
30 Cost:  9.24225 
Prediction: 
 [[148.43748]
 [185.5546 ]
 [179.03375]
 [194.6415 ]
 [143.88545]
 [107.01002]]
40 Cost:  9.189711 
Prediction: 
 [[148.4512 ]
 [185.54802]
 [179.0394 ]
 [194.64494]
 [143.87692]
 [106.99685]]
50 Cost:  9.137539 
Prediction: 
 [[148.46484]
 [185.54146]
 [179.04498]
 [194.64833]
 [143.86841]
 [106.9837 ]]
60 Cost:  9.085719 
Prediction: 
 [[148.47841]
 [185.53488]
 [179.05054]
 [194.6517 ]
 [143.8599 ]
 [106.9706 ]]
70 Cost:  

Out of range error

In [10]:
import tensorflow as tf
filename_queue = tf.train.string_input_producer(
    ['/gdrive/My Drive/Deep_learning_2102/data-01-test-score.csv'],
    shuffle = False, name = 'filename_queue')
reader = tf.TextLineReader()
key, value = reader.read(filename_queue)

#Default values, in case of empty columns. Also specifies the type of the decoded result.
record_defaults = [[0.], [0.], [0.], [0.]]
xy = tf.decode_csv(value, record_defaults = record_defaults)

#collect batches of csv in
train_x_batch, train_y_batch = \
  tf.train.batch([xy[0:-1], xy[-1:]], batch_size=10)

#placeholders for a tensor that will be always fed.
X = tf.placeholder(tf.float32, shape = [None, 3])
Y = tf.placeholder(tf.float32, shape=[None, 1])

W = tf.Variable(tf.random_normal([3,1]), name = 'weight')
b = tf.Variable(tf.random_normal([1]), name = 'bias')

#Hypothesis 
hypothesis = tf.matmul(X,W) + b

cost = tf.reduce_mean(tf.square(hypothesis - Y))

optimizer = tf.train.GradientDescentOptimizer(learning_rate = 1e-5)
train = optimizer.minimize(cost)

sess = tf.Session()

sess.run(tf.global_variables_initializer())

#Start populating the filename queue
coord = tf.train.Coordinator()
threads = tf.train.start_queue_runners(sess = sess, coord = coord)

for step in range(2001) :
  x_batch, y_batch = sess.run([train_x_batch, train_y_batch])
  cost_val, hy_val, _ = sess.run([cost, hypothesis, train], feed_dict = {X: x_batch, Y: y_batch})
  if step % 10 == 0:
    print(step, "Cost: ", cost_val, "\nPrediction:\n", hy_val)
  
  coord.request_stop()
  coord.join(threads)

# Ask my score
print("Your score will be ",
      sess.run(hypothesis, feed_dict={X: [[100, 70, 101]]}))

print("Other scores will be ",
      sess.run(hypothesis, feed_dict={X: [[60, 70, 110], [90, 100, 80]]}))

INFO:tensorflow:Error reported to Coordinator: <class 'tensorflow.python.framework.errors_impl.InvalidArgumentError'>, Field 0 in record 0 is not a valid float: # EXAM1
	 [[Node: DecodeCSV = DecodeCSV[OUT_TYPE=[DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT], field_delim=",", _device="/job:localhost/replica:0/task:0/cpu:0"](ReaderReadV2:1, DecodeCSV/record_defaults_0, DecodeCSV/record_defaults_1, DecodeCSV/record_defaults_2, DecodeCSV/record_defaults_3)]]

Caused by op 'DecodeCSV', defined at:
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py", line 16, in <module>
    app.launch_new_instance()
  File "/usr/local/lib/python3.6/dist-packages/traitlets/config/application.py", line 664, in launch_instance
    app.start()
  File "/usr/local/lib/python3.6/dist-packages/ipykernel/kernelapp.py", line

OutOfRangeError: ignored