In [ ]:
pip install tensorflow==1.0.0

     |████████████████████████████████| 44.5MB 98kB/s 
  Found existing installation: tensorflow 2.4.1
    Uninstalling tensorflow-2.4.1:
      Successfully uninstalled tensorflow-2.4.1


In [ ]:
# One hot encoding for each char in 'hello'
h = [1, 0, 0, 0]
e = [0, 1, 0, 0]
l = [0, 0, 1, 0]
o = [0, 0, 0, 1]

In [ ]:
tf.reset_default_graph()
import tensorflow as tf
import numpy as np
import pprint
pp = pprint.PrettyPrinter(indent = 4)
sess = tf.InteractiveSession()
# One cell RNN input_dim (4) -> output_dim (2)
hidden_size = 2
cell =tf.contrib.rnn.BasicLSTMCell(num_units = hidden_size)

x_data = np.array([[[1,0,0,0]]], dtype = np.float32)
outputs, _states = tf.nn.dynamic_rnn(cell,x_data, dtype = tf.float32)

sess.run(tf.global_variables_initializer())
pp.pprint(outputs.eval())

array([[[-0.07091868, -0.06882124]]], dtype=float32)


In [ ]:
# one cell RNN input_dim (4) -> out_dim (2). sequence: 5
tf.reset_default_graph()
import tensorflow as tf
import numpy as np
import pprint
pp = pprint.PrettyPrinter(indent = 4)
sess = tf.InteractiveSession()
hidden_size = 2
cell = tf.contrib.rnn.BasicLSTMCell(num_units = hidden_size)
x_data = np.array([[h,e,l,l,o]], dtype = np.float32)
print(x_data.shape)
pp.pprint(x_data)
outputs, states = tf.nn.dynamic_rnn(cell, x_data, dtype=tf.float32)
sess.run(tf.global_variables_initializer())
print(outputs.shape)
pp.pprint(outputs.eval())

(1, 5, 4)
array([[[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.],
        [0., 0., 1., 0.],
        [0., 0., 0., 1.]]], dtype=float32)
(1, 5, 2)
array([[[ 0.03743311, -0.0360768 ],
        [ 0.05799387, -0.15986383],
        [ 0.13581184,  0.01595225],
        [ 0.17828943,  0.08366446],
        [ 0.08492582,  0.10987175]]], dtype=float32)


In [ ]:
# one cell RNN input_dim (4) -> out_dim (2). sequence: 5, batch: 3
# batches 'hello', 'eolll', 'lleel'
tf.reset_default_graph()
import tensorflow as tf
import numpy as np
import pprint
pp = pprint.PrettyPrinter(indent = 4)
sess = tf.InteractiveSession()
x_data = np.array([[h,e,l,l,o], [e,o,l,l,l], [l,l,e,e,l]], dtype=np.float32)
print(x_data.shape)
pp.pprint(x_data)
cell = rnn.BasicLSTMCell(num_units=2, state_is_tuple=True)
outputs, _states = tf.nn.dynamic_rnn(cell, x_data, dtype =tf.float32)
sess.run(tf.global_variables_initializer())
print(outputs.shape)
pp.pprint(outputs.eval())

(3, 5, 4)
array([[[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.],
        [0., 0., 1., 0.],
        [0., 0., 0., 1.]],

       [[0., 1., 0., 0.],
        [0., 0., 0., 1.],
        [0., 0., 1., 0.],
        [0., 0., 1., 0.],
        [0., 0., 1., 0.]],

       [[0., 0., 1., 0.],
        [0., 0., 1., 0.],
        [0., 1., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.]]], dtype=float32)
(3, 5, 2)
array([[[ 0.16440643,  0.13468207],
        [-0.07101414,  0.21634062],
        [-0.06449985,  0.1705235 ],
        [-0.07770038,  0.16359736],
        [ 0.0211032 , -0.06294968]],

       [[-0.14067845,  0.12451714],
        [ 0.00935495, -0.10276696],
        [-0.03788789,  0.02051072],
        [-0.06298295,  0.08146115],
        [-0.07699165,  0.11316956]],

       [[-0.04158572,  0.07203034],
        [-0.0648095 ,  0.10895858],
        [-0.18737061,  0.19189544],
        [-0.2217533 ,  0.22262155],
        [-0.12069029,  0.16796857]]], dtype=float32)


In [ ]:
# cost: sequence_loss
tf.reset_default_graph()
import tensorflow as tf
import numpy as np
tf.set_random_seed(777)
sess = tf.InteractiveSession()
# [batch_size, sequence_length]
y_data = tf.constant([[1,1,1]])
# [batch_size, sequence_length, emb_dim]
prediction = tf.constant([[[0.2, 0.7], [0.6, 0.2], [0.2, 0.9]]], dtype = tf.float32)
# [batch_size * sequence_length]
weights = tf.constant([[1,1,1]], dtype = tf.float32)

sequence_loss = tf.contrib.seq2seq.sequence_loss(logits=prediction, targets=y_data, weights = weights)
sess.run(tf.global_variables_initializer())
print("Loss: ", sequence_loss.eval())

Loss:  0.5967595


In [ ]:
# cost: sequence_loss
tf.reset_default_graph()
import tensorflow as tf
import numpy as np
tf.set_random_seed(777)
sess = tf.InteractiveSession()
# [batch_size, sequence_length]
y_data = tf.constant([[1,1,1]])
# [batch_size, sequence_length, emb_dim]
prediction1 = tf.constant([[[0.3, 0.7], [0.3, 0.7], [0.3, 0.7]]], dtype = tf.float32)
prediction2 = tf.constant([[[0.1, 0.9], [0.1, 0.9], [0.1, 0.9]]], dtype = tf.float32)
# [batch_size * sequence_length]
weights = tf.constant([[1,1,1]], dtype = tf.float32)

sequence_loss1 = tf.contrib.seq2seq.sequence_loss(logits=prediction1, targets=y_data, weights = weights)
sequence_loss2 = tf.contrib.seq2seq.sequence_loss(logits=prediction2, targets=y_data, weights = weights)
sess.run(tf.global_variables_initializer())
print("Loss1: ", sequence_loss1.eval(),
      "Loss2: ", sequence_loss2.eval(),)

Loss1:  0.5130153 Loss2:  0.3711007


In [ ]:
# RNN hihello
tf.reset_default_graph()
import tensorflow as tf
import numpy as np
tf.set_random_seed(777)

idx2char = ['h', 'i', 'e', 'l', 'o']
# Teach hello: hihell -> ihello
x_data = [[0, 1, 0, 2, 3, 3]] # hihell
x_one_hot = [[[1, 0, 0, 0, 0],   # h 0
              [0, 1, 0, 0, 0],   # i 1
              [1, 0, 0, 0, 0],   # h 0
              [0, 0, 1, 0, 0],   # e 2
              [0, 0, 0, 1, 0],   # l 3
              [0, 0, 0, 1, 0]]]  # l 3

y_data = [[1, 0, 2, 3, 3, 4]] # ihello

num_classes = 5
input_dim = 5 # one-hot size
hidden_size = 5 # output from the LSTM. 5 to directly predict one-hot (input dimension)
batch_size = 1 # one sentence
sequence_length = 6 # |ihello| == 6
learning_rate = 0.1

X = tf.placeholder(tf.float32, [None, sequence_length, input_dim]) # X one-hot
Y = tf.placeholder(tf.int32, [None, sequence_length]) # Y label
cell = tf.contrib.rnn.BasicLSTMCell(num_units = hidden_size, state_is_tuple=True)
initial_state = cell.zero_state(batch_size, tf.float32)
outputs, _states = tf.nn.dynamic_rnn(cell, X, initial_state=initial_state, dtype=tf.float32)

# FC layer
X_for_fc = tf.reshape(outputs, [-1, hidden_size])
# fc_w = tf.get_variable("fc_w", [hidden_size, num_classes])
# fc_b = tf.get_variable("fc_b", [num_classes])
# outputs = tf.matmul(X_for_fc, fc_w) +fc_b
outputs = tf.contrib.layers.fully_connected(inputs = X_for_fc, num_outputs = num_classes, activation_fn = None)

# reshape out for sequence_loss
outputs = tf.reshape(outputs, [batch_size, sequence_length, num_classes])
weights = tf.ones([batch_size, sequence_length])
sequence_loss = tf.contrib.seq2seq.sequence_loss(logits=outputs, targets=Y, weights = weights)
loss = tf.reduce_mean(sequence_loss)
train = tf.train.AdamOptimizer(learning_rate = learning_rate).minimize(loss)

prediction = tf.argmax(outputs, axis = 2)

with tf.Session() as sess:
  sess.run(tf.global_variables_initializer())
  for i in range(50):
    l, _ = sess.run([loss, train], feed_dict = {X:x_one_hot, Y: y_data})
    result = sess.run(prediction, feed_dict = {X: x_one_hot})
    print(i, "loss:", l, "prediction:", result, "true Y: ", y_data)

    # print char using dic
    result_str = [idx2char[c] for c in np.squeeze(result)]
    print("\tPrediction str: ", ''.join(result_str))


0 loss: 1.6435561 prediction: [[3 3 3 3 3 3]] true Y:  [[1, 0, 2, 3, 3, 4]]
	Prediction str:  llllll
1 loss: 1.5243043 prediction: [[3 3 3 3 3 3]] true Y:  [[1, 0, 2, 3, 3, 4]]
	Prediction str:  llllll
2 loss: 1.4513379 prediction: [[3 3 3 3 3 3]] true Y:  [[1, 0, 2, 3, 3, 4]]
	Prediction str:  llllll
3 loss: 1.38718 prediction: [[3 3 3 3 3 3]] true Y:  [[1, 0, 2, 3, 3, 4]]
	Prediction str:  llllll
4 loss: 1.314246 prediction: [[3 3 3 3 3 3]] true Y:  [[1, 0, 2, 3, 3, 4]]
	Prediction str:  llllll
5 loss: 1.2205429 prediction: [[3 3 3 3 3 3]] true Y:  [[1, 0, 2, 3, 3, 4]]
	Prediction str:  llllll
6 loss: 1.1109241 prediction: [[3 0 3 3 3 4]] true Y:  [[1, 0, 2, 3, 3, 4]]
	Prediction str:  lhlllo
7 loss: 0.9984643 prediction: [[2 0 3 3 3 4]] true Y:  [[1, 0, 2, 3, 3, 4]]
	Prediction str:  ehlllo
8 loss: 0.89273125 prediction: [[2 0 2 3 3 4]] true Y:  [[1, 0, 2, 3, 3, 4]]
	Prediction str:  ehello
9 loss: 0.78947705 prediction: [[2 0 2 3 3 4]] true Y:  [[1, 0, 2, 3, 3, 4]]
	Prediction str:

In [ ]:
# Character Sequence RNN
tf.reset_default_graph()
import tensorflow as tf
import numpy as np
tf.set_random_seed(777) # reproducibility

sample = "if you want you"
idx2char = list(set(sample)) # index -> char
print(idx2char)
char2idx = {c: i for i, c in enumerate(idx2char)} # char -> index
print(char2idx)

# hyper parameters
dic_size = len(char2idx) # RNN input size (one hot size)
hidden_size = len(char2idx) # RNN output size
num_classes = len(char2idx) # final output size (RNN or softmax, etc.)
batch_size = 1 # one sample data, one batch
sequence_length = len(sample) - 1 # number of lstm rollings (unit #)
learning_rate = 0.1

sample_idx = [char2idx[c] for c in sample] # char to index
x_data = [sample_idx[:-1]] # X data sample (0 ~ n-1) hello: hell
y_data = [sample_idx[1:]] # Y label sample (1 ~ n) hello: ello

X = tf.placeholder(tf.int32, [None, sequence_length]) # X data
Y = tf.placeholder(tf.int32, [None, sequence_length]) # Y label

x_one_hot = tf.one_hot(X, num_classes) # one hot: 1 -> 0 1 0 0 0 0 0 0 0 0
cell = tf.contrib.rnn.BasicLSTMCell(num_units = hidden_size, state_is_tuple=True)
initial_state = cell.zero_state(batch_size, tf.float32)
outputs, _states = tf.nn.dynamic_rnn(cell, x_one_hot, initial_state = initial_state, dtype = tf.float32)

# FC layer
X_for_fc = tf.reshape(outputs, [-1, hidden_size])
outputs = tf.contrib.layers.fully_connected(X_for_fc, num_classes, activation_fn=None)

# reshape out for seuquence_loss
outputs = tf.reshape(outputs, [batch_size, sequence_length, num_classes])

weights = tf.ones([batch_size, sequence_length])
sequence_loss = tf.contrib.seq2seq.sequence_loss(logits = outputs, targets = Y, weights = weights)
loss = tf.reduce_mean(sequence_loss)
train = tf.train.AdamOptimizer(learning_rate = learning_rate).minimize(loss)

prediction = tf.argmax(outputs, axis = 2)

with tf.Session() as sess:
  sess.run(tf.global_variables_initializer())
  for i in range(50):
    l, _ = sess.run([loss, train], feed_dict = {X: x_data, Y: y_data})
    result = sess.run(prediction, feed_dict = {X: x_data})
    
    # print char using dic
    result_str = [idx2char[c] for c in np.squeeze(result)]

    print(i, "loss: ", l, "Prediction: ", ''.join(result_str))


['o', 't', 'n', 'f', 'i', 'u', 'w', ' ', 'y', 'a']
{'o': 0, 't': 1, 'n': 2, 'f': 3, 'i': 4, 'u': 5, 'w': 6, ' ': 7, 'y': 8, 'a': 9}
0 loss:  2.2970848 Prediction:  yyyyu yyyttyy 
1 loss:  2.1361735 Prediction:   yyouuyyyyyyou
2 loss:  1.972771 Prediction:   yyouuuyyyyyuu
3 loss:  1.7663405 Prediction:   yyou yayyyyou
4 loss:  1.5010302 Prediction:    you  ant you
5 loss:  1.2143801 Prediction:    you uant you
6 loss:  0.94900274 Prediction:    you want you
7 loss:  0.6929651 Prediction:    you want you
8 loss:  0.48511618 Prediction:    you want you
9 loss:  0.33257845 Prediction:    you want you
10 loss:  0.23032594 Prediction:    you want you
11 loss:  0.15748045 Prediction:  f you want you
12 loss:  0.10427106 Prediction:  f you want you
13 loss:  0.069349326 Prediction:  f you want you
14 loss:  0.046611685 Prediction:  f you want you
15 loss:  0.031992994 Prediction:  f you want you
16 loss:  0.02284461 Prediction:  f you want you
17 loss:  0.017265147 Prediction:  f you want you


In [ ]:
# Long Sequence RNN
tf.reset_default_graph()
import tensorflow as tf
import numpy as np
tf.set_random_seed(777) # reproducibility

sentence = "if you want to build a ship, don't drum up people together to collect wood and don't assign them tasks and work, but rather teach them to long for the endless immensity of the sea "
char_set = list(set(sentence))
char_dic = {w: i for i, w in enumerate(char_set)}

dataX = []
dataY = []

char_set = list(set(sentence))
char_dic = {w: i for i, w in enumerate(char_set)}

data_dim = len(char_set)
hidden_size = len(char_set)
num_classes = len(char_set)
seq_length = 10 # Any arbitrary number

for i in range(0, len(sentence) - seq_length):
  x_str = sentence[i: i+seq_length]
  y_str = sentence[i+1: i+seq_length+1]
  print(i, x_str, '->', y_str)

  x = [char_dic[c] for c in x_str]
  y = [char_dic[c] for c in y_str]

  dataX.append(x)
  dataY.append(y)

batch_size = len(dataX)

learning_rate = 0.1

X = tf.placeholder(tf.int32, [None, seq_length]) # X data
Y = tf.placeholder(tf.int32, [None, seq_length]) # Y label

x_one_hot = tf.one_hot(X, num_classes) # one hot: 1 -> 0 1 0 0 0 0 0 0 0 0

cell = tf.contrib.rnn.BasicLSTMCell(num_units = hidden_size, state_is_tuple=True)
initial_state = cell.zero_state(batch_size, tf.float32)
outputs, _states = tf.nn.dynamic_rnn(cell, x_one_hot, initial_state = initial_state, dtype = tf.float32)

# FC layer
X_for_fc = tf.reshape(outputs, [-1, hidden_size])
outputs = tf.contrib.layers.fully_connected(X_for_fc, num_classes, activation_fn=None)

# reshape out for seuquence_loss
outputs = tf.reshape(outputs, [batch_size, seq_length, num_classes])

weights = tf.ones([batch_size, seq_length])
sequence_loss = tf.contrib.seq2seq.sequence_loss(logits = outputs, targets = Y, weights = weights)
loss = tf.reduce_mean(sequence_loss)
train = tf.train.AdamOptimizer(learning_rate = learning_rate).minimize(loss)
prediction = tf.argmax(outputs, axis = 2)

sess = tf.Session()
sess.run(tf.global_variables_initializer())

for i in range(500):
    l, _ = sess.run([loss, train], feed_dict = {X: dataX, Y: dataY})
    result = sess.run(prediction, feed_dict = {X: dataX})

# Let's print the last char of each result to check it works
for j, result in enumerate(results):
    index = np.argmax(result, axis=1)
    if j is 0:  # print all for the first result to make a sentence
        print(''.join([char_set[t] for t in index]), end='')
    else:
        print(char_set[index[-1]], end='')



0 if you wan -> f you want
1 f you want ->  you want 
2  you want  -> you want t
3 you want t -> ou want to
4 ou want to -> u want to 
5 u want to  ->  want to b
6  want to b -> want to bu
7 want to bu -> ant to bui
8 ant to bui -> nt to buil
9 nt to buil -> t to build
10 t to build ->  to build 
11  to build  -> to build a
12 to build a -> o build a 
13 o build a  ->  build a s
14  build a s -> build a sh
15 build a sh -> uild a shi
16 uild a shi -> ild a ship
17 ild a ship -> ld a ship,
18 ld a ship, -> d a ship, 
19 d a ship,  ->  a ship, d
20  a ship, d -> a ship, do
21 a ship, do ->  ship, don
22  ship, don -> ship, don'
23 ship, don' -> hip, don't
24 hip, don't -> ip, don't 
25 ip, don't  -> p, don't d
26 p, don't d -> , don't dr
27 , don't dr ->  don't dru
28  don't dru -> don't drum
29 don't drum -> on't drum 
30 on't drum  -> n't drum u
31 n't drum u -> 't drum up
32 't drum up -> t drum up 
33 t drum up  ->  drum up p
34  drum up p -> drum up pe
35 drum up pe -> rum up peo
36

In [ ]:
# Character Sequence Softmax only
tf.reset_default_graph()
import tensorflow as tf
import numpy as np
tf.set_random_seed(777) # reproducibility

sample = "if you want you"
idx2char = list(set(sample)) # index -> char
char2idx = {c: i for i, c in enumerate(idx2char)} # char -> index

# hyper parameters
dic_size = len(char2idx) # RNN input size (one hot size)
rnn_hidden_size = len(char2idx) # RNN output size
num_classes = len(char2idx) # final output size (RNN or softmax, etc.)
batch_size = 1 # one sample data, one batch
sequence_length = len(sample) - 1 # number of lstm rollings (unit #)
learning_rate = 0.1

sample_idx = [char2idx[c] for c in sample] # char to index
x_data = [sample_idx[:-1]] # X data sample (0 ~ n-1) hello: hell
y_data = [sample_idx[1:]] # Y label sample (1 ~ n) hello: ello

X = tf.placeholder(tf.int32, [None, sequence_length]) # X data
Y = tf.placeholder(tf.int32, [None, sequence_length]) # Y label

# flatten the data (ignore batches for now). No effect if the batch size is 1
X_one_hot = tf.one_hot(X, num_classes) # one hot: 1 -> 0 1 0 0 0 0 0 0 0 0
X_for_softmax = tf.reshape(X_one_hot, [-1, rnn_hidden_size])

# softmax layer (rnn_hidden_size -> num_classes)
softmax_w = tf.get_variable("softmax_w", [rnn_hidden_size, num_classes])
softmax_b = tf.get_variable("softmax_b", [num_classes])
outputs = tf.matmul(X_for_softmax, softmax_w) + softmax_b

# expend the data (revive the batches)
outputs = tf.reshape(outputs, [batch_size, sequence_length, num_classes])
weights = tf.ones([batch_size, sequence_length])

# compute sequence cost/loss
sequence_loss = tf.contrib.seq2seq.sequence_loss(logits = outputs, targets = Y, weights = weights)
loss = tf.reduce_mean(sequence_loss)
train = tf.train.AdamOptimizer(learning_rate = learning_rate).minimize(loss)

prediction = tf.argmax(outputs, axis = 2)

with tf.Session() as sess:
  sess.run(tf.global_variables_initializer())
  for i in range(300):
    l, _ = sess.run([loss, train], feed_dict = {X: x_data, Y: y_data})
    result = sess.run(prediction, feed_dict = {X: x_data})
    
    # print char using dic
    result_str = [idx2char[c] for c in np.squeeze(result)]

    print(i, "loss: ", l, "Prediction: ", ''.join(result_str))


0 loss:  2.298801 Prediction:  faa u af f a u
1 loss:  2.0743392 Prediction:  f   u  f u   u
2 loss:  1.8675753 Prediction:  f y u ya u y u
3 loss:  1.6787077 Prediction:  f y u ya t y u
4 loss:  1.5071077 Prediction:  f y u ya t y u
5 loss:  1.3517147 Prediction:  f y u yant y u
6 loss:  1.2114003 Prediction:  f you yant you
7 loss:  1.0849184 Prediction:  f you yant you
8 loss:  0.97109383 Prediction:  f you yant you
9 loss:  0.86893386 Prediction:  f you yant you
10 loss:  0.777571 Prediction:  f you yant you
11 loss:  0.696199 Prediction:  f you yant you
12 loss:  0.6240539 Prediction:  f you yant you
13 loss:  0.56042016 Prediction:  f you yant you
14 loss:  0.5046345 Prediction:  f you yant you
15 loss:  0.45607296 Prediction:  f you yant you
16 loss:  0.41412863 Prediction:  f you yant you
17 loss:  0.3781841 Prediction:  f you yant you
18 loss:  0.34759095 Prediction:  f you yant you
19 loss:  0.321667 Prediction:  f you yant you
20 loss:  0.29971808 Prediction:  f you yant you

In [ ]:
# Long Sequence RNN with softmax
from __future__ import print_function

tf.reset_default_graph()
import tensorflow as tf
import numpy as np
from tensorflow.contrib import rnn
tf.set_random_seed(777) # reproducibility

sentence = "if you want to build a ship, don't drum up people together to collect wood and don't assign them tasks and work, but rather teach them to long for the endless immensity of the sea "
char_set = list(set(sentence))
char_dic = {w: i for i, w in enumerate(char_set)}

dataX = []
dataY = []

char_set = list(set(sentence))
char_dic = {w: i for i, w in enumerate(char_set)}

data_dim = len(char_set)
hidden_size = len(char_set)
num_classes = len(char_set)
seq_length = 10 # Any arbitrary number

for i in range(0, len(sentence) - seq_length):
  x_str = sentence[i: i+seq_length]
  y_str = sentence[i+1: i+seq_length+1]
  print(i, x_str, '->', y_str)

  x = [char_dic[c] for c in x_str]
  y = [char_dic[c] for c in y_str]

  dataX.append(x)
  dataY.append(y)

batch_size = len(dataX)

learning_rate = 0.1

X = tf.placeholder(tf.int32, [None, seq_length]) # X data
Y = tf.placeholder(tf.int32, [None, seq_length]) # Y label

X_one_hot = tf.one_hot(X, num_classes) # one hot: 1 -> 0 1 0 0 0 0 0 0 0 0
print(X_one_hot) #check out the shape

# Make a lstm cell with hidden_size (each unit output vector size)
def lstm_cell():
  cell = rnn.BasicLSTMCell(hidden_size, state_is_tuple=True)
  return cell
 
multi_cells = tf.contrib.rnn.MultiRNNCell([lstm_cell() for _ in range(2)], state_is_tuple=True)

# outputs: unfolding size x hidden size, state = hidden size
outputs, _states = tf.nn.dynamic_rnn(multi_cells, X_one_hot, dtype = tf.float32)

# FC layer
X_for_fc = tf.reshape(outputs, [-1, hidden_size])
outputs = tf.contrib.layers.fully_connected(X_for_fc, num_classes, activation_fn=None)

# reshape out for seuquence_loss
outputs = tf.reshape(outputs, [batch_size, seq_length, num_classes])

weights = tf.ones([batch_size, seq_length])
sequence_loss = tf.contrib.seq2seq.sequence_loss(logits = outputs, targets = Y, weights = weights)
loss = tf.reduce_mean(sequence_loss)
train = tf.train.AdamOptimizer(learning_rate = learning_rate).minimize(loss)
prediction = tf.argmax(outputs, axis = 2)

sess = tf.Session()
sess.run(tf.global_variables_initializer())

for i in range(500):
    _, l, _ = sess.run([train, loss, outputs], feed_dict = {X: dataX, Y: dataY})
    for j, result in enumerate(results):
      index = np.argmax(result, axis = 1)
      print(i, j, ''.join([char_set[t] for t in index]), 1)

# Let's print the last char of each result to check it works
for j, result in enumerate(results):
    index = np.argmax(result, axis=1)
    if j is 0:  # print all for the first result to make a sentence
        print(''.join([char_set[t] for t in index]), end='')
    else:
        print(char_set[index[-1]], end='')



스트리밍 출력 내용이 길어서 마지막 5000줄이 삭제되었습니다.
470 101 iand work, 1
470 102 tnd work,  1
470 103 nd work, b 1
470 104 d work, bu 1
470 105  aork, but 1
470 106 tork, but  1
470 107 ook, but r 1
470 108   , but ra 1
470 109  , but rat 1
470 110 s but rath 1
470 111  but rathe 1
470 112 tut rather 1
470 113 ut rather  1
470 114 m rather t 1
470 115 hrather te 1
470 116 tather tea 1
470 117  ther teac 1
470 118 nher teach 1
470 119 hem teach  1
470 120 em teach t 1
470 121 r teach th 1
470 122  thach the 1
470 123 toach them 1
470 124 hach them  1
470 125 rch them t 1
470 126 nh them to 1
470 127 t them to  1
470 128 ethem to l 1
470 129 toem to lo 1
470 130 hem to lon 1
470 131 em to long 1
470 132 r ta long  1
470 133  ta long f 1
470 134 to cong fo 1
470 135 h cong for 1
470 136  cong for  1
470 137 tong for t 1
470 138 eng for th 1
470 139  ' for the 1
470 140 d for the  1
470 141  for the e 1
470 142 tor the en 1
470 143  r the end 1
470 144   the endl 1
470 145  the endle 1
470 146 toemendles 

Error in x_data shape

In [ ]:
# Dynammic RNN
tf.reset_default_graph()
import tensorflow as tf
import numpy as np
sess = tf.InteractiveSession()
x_data = np.array([[[...]]], dtype=np.float32)
#x_data = np.array([[[h,e,l,l,o], [e,o,l,l,l], [l,l,e,e,l]]], dtype=np.float32)
hidden_size = 2
cell = rnn.BasicLSTMCell(num_units = hidden_size, state_is_tuple = True)
outputs, _sates = tf.nn.dynamic_rnn(cell, x_data, sequence_length = [5, 3, 4], dtype=tf.float32)
sess.run(tf.global_variables_initializer())
print(outputs.eval())

NameError: ignored

In [84]:
# predict stock prices using basic RNN
tf.reset_default_graph()
import tensorflow as tf
import numpy as np
import matplotlib
import matplotlib.pyplot as plt
from google.colab import drive
drive.mount('/gdrive', force_remount=True)
tf.set_random_seed(777)

def MinMaxScaler(data):
  numerator = data - np.min(data, 0)
  denominator = np.max(data, 0) - np.min(data, 0)
  # noise term prevents the zero division
  return numerator / (denominator + 1e-7)

# train Parameters
seq_length = 7
data_dim = 5
hidden_dim = 10
output_dim = 1
learning_rate = 0.01
iterations = 500

# Open, High, Low, Volumne, Close
xy = np.loadtxt('/gdrive/My Drive/Deep_learning_2102/data-02-stock_daily.csv', delimiter=',')
xy = xy[::-1] # reverse order (chronically ordered)

# train/test split
train_size = int(len(xy)*0.7)
train_set = xy[0:train_size]
test_set = xy[train_size - seq_length:] #Index from [train_size - seq_length] to utilize past sequence

# Scale each
train_set = MinMaxScaler(train_set)
test_set = MinMaxScaler(test_set)

# build datasets
def build_dataset(time_series, seq_length):
  dataX = []
  dataY = []
  for i in range(0, len(time_series)-seq_length):
    _x = time_series[i:i+seq_length, :]
    _y = time_series[i+seq_length, [-1]] # Next close price
    print(_x, "->", _y)
    dataX.append(_x)
    dataY.append(_y)
  return np.array(dataX), np.array(dataY)

trainX, trainY = build_dataset(train_set, seq_length)
testX, testY = build_dataset(test_set, seq_length)

# input place holders
X = tf.placeholder(tf.float32, [None, seq_length, data_dim])
Y = tf.placeholder(tf.float32, [None, 1])

# build a LSTM network
cell = tf.contrib.rnn.BasicLSTMCell(num_units = hidden_dim, state_is_tuple = True, activation = tf.tanh)
outputs, _states = tf.nn.dynamic_rnn(cell, X, dtype = tf.float32)
Y_pred = tf.contrib.layers.fully_connected(outputs[:, -1], output_dim, activation_fn = None) # We use the last cell's output

# cost / loss
loss = tf.reduce_sum(tf.square(Y_pred - Y)) # sum of the squares
#optimizer
optimizer = tf.train.AdamOptimizer(learning_rate)
train = optimizer.minimize(loss)

#RMSE
targets = tf.placeholder(tf.float32, [None, 1])
predictions = tf.placeholder(tf.float32, [None, 1])
rmse = tf.sqrt(tf.reduce_mean(tf.square(targets - predictions)))

with tf.Session() as sess:
  init = tf.global_variables_initializer()
  sess.run(init)

  # Training step
  for i in range(iterations):
    _, step_loss = sess.run([train, loss], feed_dict = {X: trainX, Y: trainY})
    print("[step: {}] loss: {}".format(i, step_loss))

  # Test step
  test_predict = sess.run(Y_pred, feed_dict = {X: testX})
  rmse_val = sess.run(rmse, feed_dict = {targets: testY, predictions: test_predict})
  print("RMSE: {}".format(rmse_val))

  # Plot predictions
  plt.plot(testY)
  plt.plot(test_predict)
  plt.xlabel("Time Period")
  plt.ylabel("Stock Price")
  plt.show()

스트리밍 출력 내용이 길어서 마지막 5000줄이 삭제되었습니다.
 [0.32230868 0.32843538 0.34794237 0.08773864 0.34519007]
 [0.32465462 0.31890794 0.34351041 0.12027427 0.32762237]
 [0.31706442 0.31822758 0.34524656 0.09039168 0.3339946 ]
 [0.29653629 0.2983222  0.2951278  0.18775657 0.27829953]
 [0.26134529 0.27215599 0.26953141 0.17453617 0.25883077]] -> [0.28375646]
[[0.33034738 0.32625771 0.35609378 0.08286278 0.33962757]
 [0.32230868 0.32843538 0.34794237 0.08773864 0.34519007]
 [0.32465462 0.31890794 0.34351041 0.12027427 0.32762237]
 [0.31706442 0.31822758 0.34524656 0.09039168 0.3339946 ]
 [0.29653629 0.2983222  0.2951278  0.18775657 0.27829953]
 [0.26134529 0.27215599 0.26953141 0.17453617 0.25883077]
 [0.2566532  0.27008035 0.27400631 0.12722058 0.28375646]] -> [0.25531025]
[[0.32230868 0.32843538 0.34794237 0.08773864 0.34519007]
 [0.32465462 0.31890794 0.34351041 0.12027427 0.32762237]
 [0.31706442 0.31822758 0.34524656 0.09039168 0.3339946 ]
 [0.29653629 0.2983222  0.2951278  0.18775657 0.27829953]
 [