In [1]:
pip install tensorflow==1.0.0

     |████████████████████████████████| 44.5MB 106kB/s 
  Found existing installation: tensorflow 2.4.1
    Uninstalling tensorflow-2.4.1:
      Successfully uninstalled tensorflow-2.4.1


In [2]:
import tensorflow as tf
x_data = [[1,2], [2,3], [3,1], [4,3], [5,3], [6,2]]
y_data = [[0], [0], [0], [1], [1], [1]]
#placeholders for a tensor that will be always fed.
X = tf.placeholder(tf.float32, shape = [None, 2])
Y = tf.placeholder(tf.float32, shape = [None, 1])

W = tf.Variable(tf.random_normal([2,1]), name ='weight')
b = tf.Variable(tf.random_normal([1]), name = 'bias')
#Hypothesis using sigmoid tf.div(1., 1. + tf.exp(tf.matmul(X,W)))
hypothesis = tf.sigmoid(tf.matmul(X,W)+b)
#cost/loss function
cost = -tf.reduce_mean(Y * tf.log(hypothesis) + (1 - Y) * tf.log(1 - hypothesis))
train = tf.train.GradientDescentOptimizer(learning_rate = 0.01).minimize(cost)

#Accuracy computation
#True if hypothesis>0.5 else False
predicted = tf.cast(hypothesis > 0.5, dtype = tf.float32)
accuracy = tf.reduce_mean(tf.cast(tf.equal(predicted, Y), dtype= tf.float32))

#Launch graph
with tf.Session() as sess:
  #Initialize TensorFlow variables
  sess.run(tf.global_variables_initializer())

  for step in range(10001) :
    cost_val, _ = sess.run([cost, train], feed_dict = {X: x_data, Y: y_data})
    if step % 200 == 0:
      print(step, cost_val)

      # Accuracy report
      h, c, a = sess.run([hypothesis, predicted, accuracy], feed_dict = {X: x_data, Y: y_data})
      print("\nHypothesis: \n", h, "\nCorrect (Y): \n", c, "\nAccuracy: ", a)

/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/dtypes.py:471: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/dtypes.py:472: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/dtypes.py:473: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/dtypes.py:474: FutureWarning: Passing (type, 1) or 

0 3.6927578

Hypothesis: 
 [[0.07666344]
 [0.01506716]
 [0.01780762]
 [0.00179293]
 [0.00061508]
 [0.00039206]] 
Correct (Y): 
 [[0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]] 
Accuracy:  0.5
200 0.5490534

Hypothesis: 
 [[0.44248176]
 [0.47479635]
 [0.65866995]
 [0.64065534]
 [0.7145864 ]
 [0.812552  ]] 
Correct (Y): 
 [[0.]
 [0.]
 [1.]
 [1.]
 [1.]
 [1.]] 
Accuracy:  0.8333333
400 0.4936885

Hypothesis: 
 [[0.34878978]
 [0.37965295]
 [0.6828395 ]
 [0.6283978 ]
 [0.7376007 ]
 [0.8717549 ]] 
Correct (Y): 
 [[0.]
 [0.]
 [1.]
 [1.]
 [1.]
 [1.]] 
Accuracy:  0.8333333
600 0.46156177

Hypothesis: 
 [[0.29007518]
 [0.32376423]
 [0.69341093]
 [0.6247809 ]
 [0.7564104 ]
 [0.9021216 ]] 
Correct (Y): 
 [[0.]
 [0.]
 [1.]
 [1.]
 [1.]
 [1.]] 
Accuracy:  0.8333333
800 0.43896094

Hypothesis: 
 [[0.25068498]
 [0.28899017]
 [0.6957341 ]
 [0.62500274]
 [0.7714299 ]
 [0.9192993 ]] 
Correct (Y): 
 [[0.]
 [0.]
 [1.]
 [1.]
 [1.]
 [1.]] 
Accuracy:  0.8333333
1000 0.42087248

Hypothesis: 
 [[0.2225457 ]
 [0.2661768 ]
 [

In [6]:
import tensorflow as tf
import numpy as np
from google.colab import drive
drive.mount('/gdrive', force_remount=True)
tf.set_random_seed(777)
xy = np.loadtxt('/gdrive/My Drive/Deep_learning_2102/data-03-diabetes.csv', delimiter = ',', dtype = np.float32)
x_data = xy[:, 0:-1]
y_data = xy[:, [-1]]

# placeholders for a tensor that will be always fed.
X = tf.placeholder(tf.float32, shape = [None, 8])
Y = tf.placeholder(tf.float32, shape = [None, 1])

W = tf.Variable(tf.random_normal([8,1]), name = 'weight')
b = tf.Variable(tf.random_normal([1]), name = 'bias')

#Hypothesis using sigmoid: tf.div(1., 1. + exp(tf.matmul(X, W)))
hypothesis = tf.sigmoid(tf.matmul(X,W) + b)
# cost/loss function
cost = -tf.reduce_mean(Y * tf.log(hypothesis) + (1 - Y) * tf.log(1 - hypothesis))
train = tf.train.GradientDescentOptimizer(learning_rate = 0.01).minimize(cost)

#Accuracy computation
#True if hypothesis > 0.5 else False
predicted = tf.cast(hypothesis > 0.5, dtype = tf.float32)
accuracy = tf.reduce_mean(tf.cast(tf.equal(predicted, Y), dtype = tf.float32))

#Launch graph
with tf.Session() as sess:
  sess.run(tf.global_variables_initializer())

  feed = {X: x_data, Y: y_data}
  for step in range(10001):
    sess.run(train, feed_dict = feed)
    if step % 200 == 0 :
      print(step, sess.run(cost, feed_dict = feed))

  # Accuracy report
  h, c, a = sess.run([hypothesis, predicted, accuracy], feed_dict = feed)
  print("\nHypothesis: \n",h, "\n Corrct (Y): \n", c, "Accracy: ", a)

Mounted at /gdrive
0 0.83234036
200 0.7156101
400 0.66930425
600 0.6477369
800 0.63315135
1000 0.62087697
1200 0.6098456
1400 0.5997825
1600 0.5905751
1800 0.5821453
2000 0.57442456
2200 0.5673506
2400 0.56086564
2600 0.55491674
2800 0.5494552
3000 0.5444364
3200 0.5398201
3400 0.5355695
3600 0.5316515
3800 0.52803594
4000 0.5246958
4200 0.5216065
4400 0.5187459
4600 0.5160942
4800 0.5136332
5000 0.5113466
5200 0.50921977
5400 0.5072394
5600 0.5053933
5800 0.5036707
6000 0.50206155
6200 0.5005568
6400 0.4991487
6600 0.49782944
6800 0.49659228
7000 0.495431
7200 0.49433997
7400 0.49331445
7600 0.4923491
7800 0.49143988
8000 0.49058297
8200 0.48977455
8400 0.4890113
8600 0.48829025
8800 0.4876085
9000 0.48696345
9200 0.48635262
9400 0.48577395
9600 0.48522532
9800 0.48470482
10000 0.48421076

Hypothesis: 
 [[0.40791893]
 [0.92478204]
 [0.19705391]
 [0.93908405]
 [0.13696985]
 [0.74603915]
 [0.9311439 ]
 [0.5690998 ]
 [0.26888072]
 [0.53455937]
 [0.73237807]
 [0.17177723]
 [0.21241026]
 [